list:
    path:     /list/{offset}/{typeIdentifier}
    defaults: { _controller: EzSystemsExtendingPlatformUIConferenceBundle:List:list, offset: 0, typeIdentifier: "" }
    requirements:
        offset: \d+
        typeIdentifier: "[a-zA-Z_]+"
