services:
    ez_systems_extending_platform_uiconference.service.content_searcher:
        class: EzSystems\ExtendingPlatformUIConferenceBundle\Service\ContentSearcher
        arguments: ["@ezpublish.api.service.search"]
