services:
#    ez_systems_extending_platform_ui_conference.example:
#        class: EzSystems\ExtendingPlatformUIConferenceBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
