system:
    default:
        yui:
            modules:
                ezconf-listapplugin:
                    dependencyOf: ['ez-platformuiapp']
                    requires: ['ez-pluginregistry', 'plugin', 'base', 'ezconf-listview']
                    path: "%extending_platformui.public_dir%/js/apps/plugins/ezconf-listappplugin.js"
                ezconf-listview:
                    requires: ['ez-templatebasedview', 'ezconflistview-ez-template']
                    path: "%extending_platformui.public_dir%/js/views/ezconf-listview.js"
                ezconflistview-ez-template:
                    type: 'template'
                    path: "%extending_platformui.public_dir%/templates/ezconflistview.hbt"
                ezconf-navigationplugin:
                    requires: ['ez-pluginregistry', 'ez-viewservicebaseplugin', 'ez-navigationitemview']
                    dependencyOf: ['ez-navigationhubviewservice']
                    path: "%extending_platformui.public_dir%/js/views/services/plugins/ezconf-navigationplugin.js"
                ezconf-listviewservice:
                     requires: ['ez-viewservice']
                     path: "%extending_platformui.public_dir%/js/views/services/ezconf-listviewservice.js"
